### PR TITLE
Update bot.js

### PR DESCRIPTION
**Pull request by DudeVoid**
Why `client.user.setPresence`?

### CODE REVIEW

**Comment by DudeVoid** [comment]
The only reason why `.setGame` doesn't work anymore is because you weren't on the latest update.

**Comment by DudeVoid** [comment]
`npm update discord.js` in the cmd line to update. 👍

**Comment by goddyCodes** [comment]
bitch that shit doesn't work

**Comment by DudeVoid** [comment]
Yes it does.

**Comment by DudeVoid** [comment]
Read what I said.

**Comment by TotallyTriggeredTigers** [comment]
void stfu no one cares and you don't need to help me with my bot anymore

**Comment by goddyCodes** [comment]
yes

**Comment by DudeVoid** [comment]
Um

**Comment by DudeVoid** [comment]
I'm trying to fucking help you.

**Comment by DudeVoid** [comment]
I doubt you even **tried** my method.

**Comment by TotallyTriggeredTigers** [comment]
um

**Comment by TotallyTriggeredTigers** [comment]
I don't fucking care.

**Comment by DudeVoid** [comment]
Ok bitch

**Comment by DudeVoid** [comment]
Lol it closed.

**Comment by TotallyTriggeredTigers** [comment]
lol ok

**Comment by DudeVoid** [comment]
:)

**Pull request closed without merging**
